// Interactive Mock Storage for Live GitHub Pages Demo Mode

const STORAGE_KEYS = {
  USERS: 'spm_demo_users_v6',
  STUDENTS: 'spm_demo_students_v6',
  COMPANIES: 'spm_demo_companies_v6',
  JOBS: 'spm_demo_jobs_v6',
  APPLICATIONS: 'spm_demo_applications_v6',
}

const DEFAULT_USERS = [
  { id: 1, name: 'Chakri (Admin)', email: 'kcr1606137@gmail.com', role: 'ADMIN', token: 'demo-admin-jwt-token' },
  { id: 101, name: 'Chakri', email: 'chakri@gmail.com', role: 'ADMIN', token: 'demo-admin-token-2' },
  { id: 2, name: 'Sai Charan (Perficient)', email: 'saicharan@gmail.com', role: 'COMPANY', token: 'demo-saicharan-jwt-token' },
  { id: 3, name: 'Harsha (Microsoft)', email: 'harsha@gmail.com', role: 'COMPANY', token: 'demo-harsha-jwt-token' },
  { id: 4, name: 'Bhargav (Student)', email: 'bhargav@gmail.com', role: 'STUDENT', token: 'demo-bhargav-jwt-token' },
  { id: 5, name: 'Anurag (Student)', email: 'anurag@gmail.com', role: 'STUDENT', token: 'demo-anurag-jwt-token' },
  { id: 6, name: 'Srujan (Student)', email: 'srujan@gmail.com', role: 'STUDENT', token: 'demo-srujan-jwt-token' },
  { id: 7, name: 'Indra (Accenture)', email: 'indra@gmail.com', role: 'COMPANY', token: 'demo-indra-jwt-token' },
  { id: 9, name: 'Rishitha (Student)', email: 'rishitha@gmail.com', role: 'STUDENT', token: 'demo-rishitha-jwt-token' },
  { id: 10, name: 'Nitya (Student)', email: 'nitya@gmail.com', role: 'STUDENT', token: 'demo-nitya-jwt-token' },
]

const DEFAULT_STUDENTS = [
  {
    id: 1,
    userId: 6,
    user: { id: 6, name: 'Nitya', email: 'nitya@gmail.com' },
    college: 'VNIT Nagpur',
    degree: 'B.Tech',
    branch: 'CSE',
    graduationYear: 2025,
    cgpa: 8.50,
    phone: '6300373746',
    resumeUrl: 'https://Nitya.com',
  },
  {
    id: 2,
    userId: 8,
    user: { id: 8, name: 'Srujan', email: 'srujan@gmail.com' },
    college: 'NIT Trichy',
    degree: 'B.Tech',
    branch: 'ECE',
    graduationYear: 2026,
    cgpa: 7.15,
    phone: '9177323879',
    resumeUrl: 'https://srujan.com',
  },
  {
    id: 3,
    userId: 7,
    user: { id: 7, name: 'Bhargav', email: 'bhargav@gmail.com' },
    college: 'NIT Surat',
    degree: 'B.Tech',
    branch: 'ECE',
    graduationYear: 2026,
    cgpa: 8.29,
    phone: '8106821142',
    resumeUrl: 'https://Bhargav.com',
  },
  {
    id: 4,
    userId: 9,
    user: { id: 9, name: 'Anurag', email: 'anurag@gmail.com' },
    college: 'NIT Warangal',
    degree: 'BTech',
    branch: 'CSE',
    graduationYear: 2026,
    cgpa: 7.50,
    phone: '9063443206',
    resumeUrl: 'https://Anurag.com',
  },
  {
    id: 5,
    userId: 5,
    user: { id: 5, name: 'Rishitha', email: 'rishitha@gmail.com' },
    college: 'VNIT Nagpur',
    degree: 'B.Tech',
    branch: 'CSE',
    graduationYear: 2025,
    cgpa: 9.00,
    phone: '8125622401',
    resumeUrl: 'https://rishitha.com',
  },
]

const DEFAULT_COMPANIES = [
  {
    id: 1,
    userId: 2,
    companyName: 'Microsoft',
    user: { id: 2, name: 'Harsha', email: 'harsha@gmail.com' },
    location: 'Hyderabad',
    website: 'https://www.microsoft.com/en-in/',
    description: 'Software development company',
  },
  {
    id: 2,
    userId: 3,
    companyName: 'Perficient',
    user: { id: 3, name: 'Sai Charan', email: 'saicharan@gmail.com' },
    location: 'Nagpur',
    website: 'https://www.perficient.com/',
    description: 'Associate Technical Consultant',
  },
  {
    id: 3,
    userId: 4,
    companyName: 'Accenture',
    user: { id: 4, name: 'Indra', email: 'indra@gmail.com' },
    location: 'Bangalore',
    website: 'https://www.accenture.com/in-en',
    description: 'AI Engineer',
  },
]

const DEFAULT_JOBS = [
  {
    id: 1,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'Java Backend Developer',
    description: 'Design and develop scalable microservices, REST APIs, and distributed architectures in Java and Spring Boot.',
    location: 'Hyderabad',
    salary: 1450000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.50,
    experienceRequired: '0-2 years',
    deadline: '2026-09-30',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 2,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'React Frontend Developer',
    description: 'Build modern, responsive, and high-performance UI components with React, Redux, and modern CSS.',
    location: 'Hyderabad',
    salary: 1300000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.00,
    experienceRequired: '0-2 years',
    deadline: '2026-08-30',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 3,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'Full Stack Developer',
    description: 'Develop end-to-end web applications combining Spring Boot backends and React frontends.',
    location: 'Hyderabad',
    salary: 1600000,
    jobType: 'FULL_TIME',
    minimumCgpa: 8.00,
    experienceRequired: '0-2 years',
    deadline: '2026-08-30',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 4,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'Python Developer',
    description: 'Create data-driven backends, automation pipelines, and scalable microservices.',
    location: 'Hyderabad',
    salary: 1350000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.50,
    experienceRequired: '0-2 years',
    deadline: '2026-08-10',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 5,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'Software Engineer',
    description: 'Write clean, efficient, and maintainable software for high-scale enterprise systems.',
    location: 'Hyderabad',
    salary: 1500000,
    jobType: 'FULL_TIME',
    minimumCgpa: 8.00,
    experienceRequired: '0-2 years',
    deadline: '2026-08-30',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 6,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'Data Analyst',
    description: 'Extract, transform, and visualize complex business datasets with SQL and BI dashboards.',
    location: 'Hyderabad',
    salary: 1150000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.00,
    experienceRequired: '0-2 years',
    deadline: '2026-08-10',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 7,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'Machine Learning Engineer',
    description: 'Design, train, and deploy predictive ML models and neural architectures.',
    location: 'Hyderabad',
    salary: 2100000,
    jobType: 'FULL_TIME',
    minimumCgpa: 8.50,
    experienceRequired: '0-2 years',
    deadline: '2026-08-30',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 8,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'DevOps Engineer',
    description: 'Manage CI/CD pipelines, container orchestration with Docker/K8s, and cloud infra.',
    location: 'Bengaluru',
    salary: 1750000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.50,
    experienceRequired: '0-2 years',
    deadline: '2026-08-10',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 9,
    companyId: 1,
    company: DEFAULT_COMPANIES[0],
    title: 'Cloud Engineer',
    description: 'Architect, deploy, and maintain secure, highly available Azure cloud infrastructure.',
    location: 'Hyderabad',
    salary: 1800000,
    jobType: 'FULL_TIME',
    minimumCgpa: 8.00,
    experienceRequired: '0-2 years',
    deadline: '2026-08-30',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 10,
    companyId: 2,
    company: DEFAULT_COMPANIES[1],
    title: 'Database Administrator',
    description: 'Optimize relational database performance, manage high-availability clusters and backups.',
    location: 'Hyd',
    salary: 1200000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.00,
    experienceRequired: '0',
    deadline: '2026-09-05',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 11,
    companyId: 3,
    company: DEFAULT_COMPANIES[2],
    title: 'QA Automation Engineer',
    description: 'Develop automated testing frameworks using Selenium, JUnit, and Cypress.',
    location: 'Hyd',
    salary: 1050000,
    jobType: 'FULL_TIME',
    minimumCgpa: 6.50,
    experienceRequired: '0',
    deadline: '2026-09-05',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 12,
    companyId: 3,
    company: DEFAULT_COMPANIES[2],
    title: 'Cybersecurity Analyst',
    description: 'Perform vulnerability assessments, network security audits, and penetration testing.',
    location: 'Hyd',
    salary: 1900000,
    jobType: 'FULL_TIME',
    minimumCgpa: 8.00,
    experienceRequired: '0',
    deadline: '2026-08-14',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 13,
    companyId: 3,
    company: DEFAULT_COMPANIES[2],
    title: 'Mobile App Developer',
    description: 'Build native and cross-platform mobile applications using Flutter and React Native.',
    location: 'Hyd',
    salary: 1400000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.50,
    experienceRequired: '0',
    deadline: '2026-09-05',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 14,
    companyId: 3,
    company: DEFAULT_COMPANIES[2],
    title: 'UI/UX Designer',
    description: 'Create wireframes, user journeys, interactive prototypes, and design systems in Figma.',
    location: 'Hyd',
    salary: 1100000,
    jobType: 'FULL_TIME',
    minimumCgpa: 6.50,
    experienceRequired: '0',
    deadline: '2026-09-05',
    createdAt: '2026-08-15T10:00:00',
  },
  {
    id: 15,
    companyId: 3,
    company: DEFAULT_COMPANIES[2],
    title: 'System Engineer',
    description: 'Configure, maintain, and monitor enterprise server infrastructure and networks.',
    location: 'Hyd',
    salary: 1250000,
    jobType: 'FULL_TIME',
    minimumCgpa: 7.00,
    experienceRequired: '0',
    deadline: '2026-09-05',
    createdAt: '2026-08-15T10:00:00',
  },
]

const DEFAULT_APPLICATIONS = [
  {
    id: 1,
    studentId: 1,
    student: DEFAULT_STUDENTS[0],
    jobId: 1,
    job: DEFAULT_JOBS[0],
    status: 'SELECTED',
    appliedAt: '2026-08-15T10:30:00',
  },
  {
    id: 2,
    studentId: 1,
    student: DEFAULT_STUDENTS[0],
    jobId: 3,
    job: DEFAULT_JOBS[2],
    status: 'SHORTLISTED',
    appliedAt: '2026-08-10T14:15:00',
  },
  {
    id: 3,
    studentId: 2,
    student: DEFAULT_STUDENTS[1],
    jobId: 8,
    job: DEFAULT_JOBS[7],
    status: 'SELECTED',
    appliedAt: '2026-08-12T09:00:00',
  },
  {
    id: 4,
    studentId: 3,
    student: DEFAULT_STUDENTS[2],
    jobId: 4,
    job: DEFAULT_JOBS[3],
    status: 'PENDING',
    appliedAt: '2026-08-14T16:00:00',
  },
  {
    id: 5,
    studentId: 4,
    student: DEFAULT_STUDENTS[3],
    jobId: 14,
    job: DEFAULT_JOBS[13],
    status: 'SHORTLISTED',
    appliedAt: '2026-08-16T11:00:00',
  },
  {
    id: 6,
    studentId: 5,
    student: DEFAULT_STUDENTS[4],
    jobId: 2,
    job: DEFAULT_JOBS[1],
    status: 'PENDING',
    appliedAt: '2026-08-16T12:30:00',
  },
]

function getFromStorage(key, fallback) {
  try {
    const item = localStorage.getItem(key)
    if (!item) {
      localStorage.setItem(key, JSON.stringify(fallback))
      return fallback
    }
    return JSON.parse(item)
  } catch (e) {
    return fallback
  }
}

function saveToStorage(key, data) {
  try {
    localStorage.setItem(key, JSON.stringify(data))
  } catch (e) {
    console.error('Failed to save to storage', e)
  }
}

export const MockStore = {
  getUsers: () => getFromStorage(STORAGE_KEYS.USERS, DEFAULT_USERS),
  getStudents: () => getFromStorage(STORAGE_KEYS.STUDENTS, DEFAULT_STUDENTS),
  saveStudents: (data) => saveToStorage(STORAGE_KEYS.STUDENTS, data),
  getCompanies: () => getFromStorage(STORAGE_KEYS.COMPANIES, DEFAULT_COMPANIES),
  saveCompanies: (data) => saveToStorage(STORAGE_KEYS.COMPANIES, data),
  getJobs: () => getFromStorage(STORAGE_KEYS.JOBS, DEFAULT_JOBS),
  saveJobs: (data) => saveToStorage(STORAGE_KEYS.JOBS, data),
  getApplications: () => getFromStorage(STORAGE_KEYS.APPLICATIONS, DEFAULT_APPLICATIONS),
  saveApplications: (data) => saveToStorage(STORAGE_KEYS.APPLICATIONS, data),
  resetDemoData: () => {
    localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(DEFAULT_USERS))
    localStorage.setItem(STORAGE_KEYS.STUDENTS, JSON.stringify(DEFAULT_STUDENTS))
    localStorage.setItem(STORAGE_KEYS.COMPANIES, JSON.stringify(DEFAULT_COMPANIES))
    localStorage.setItem(STORAGE_KEYS.JOBS, JSON.stringify(DEFAULT_JOBS))
    localStorage.setItem(STORAGE_KEYS.APPLICATIONS, JSON.stringify(DEFAULT_APPLICATIONS))
  },
}
